Tag libssh
Following commits cause this build failure:

In file included from ../src/pki_container_openssh.c:35:0:
../src/pki_container_openssh.c: In function ‘pki_openssh_import_privkey_blob’:
../include/libssh/priv.h:290:61: error: lvalue required as unary ‘&’ operand
         memset((s), '\0', (n)); __asm__ volatile("" : : "r"(&(s)) : "memory"); \
                                                             ^
../src/pki_container_openssh.c:112:9: note: in expansion of macro ‘explicit_bzero’
         explicit_bzero(ssh_string_data(privkey), ED25519_SK_LEN);
         ^