Enable P2P code in Flatpak
The default non-P2P code fails to build against GLib master, because of
the new autolist:

../common/flatpak-dir.h: In function ‘glib_listautoptr_cleanup_OstreeRepoFinderResult’:
../common/flatpak-dir.h:148:56: error: expected expression before ‘void’
 G_DEFINE_AUTOPTR_CLEANUP_FUNC (OstreeRepoFinderResult, void)