manifest: Disable vala support in vte
Its failing to build:
rm -f ../../../bindings/vala/vte_2_91_vala.stamp && echo stamp > ../../../bindings/vala/vte_2_91_vala.stamp-t
CDPATH="${ZSH_VERSION+.}:" && cd ../../../bindings/vala && /usr/bin/valac --target-glib=2.38 --pkg=posix --pkg=gio-2.0 --pkg=gtk+-3.0 --gresources app.gresource.xml  --disable-since-check -D GTK_3_16  -C app.vala config.vapi ./vte-2.91.vapi
error: ./vte-2.91.vapi not found