Tag Totem
The Meson build is failing because of some Meson issue:

FAILED: src/plugins/sample-vala/sample-vala@sha/totem-sample-vala-plugin.c src/plugins/sample-vala/sample-vala.h src/plugins/sample-vala/sample-vala.vapi
valac '-C' '--debug' '--pkg' 'libpeas-1.0' '--pkg' 'gtk+-3.0' '-d' 'src/plugins/sample-vala/sample-vala@sha' '--library=sample-vala' '-H' 'src/plugins/sample-vala/sample-vala.h' '--vapi' '../sample-vala.vapi' '--girdir=/ostbuild/source/totem/_build/src' '--pkg=Totem-1.0' ../src/plugins/sample-vala/totem-sample-vala-plugin.vala
error: Package `Totem-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories

The Totem GIR is not built before the Vala plugins.