Disable -Werror for Epiphany
Fails to build because of libxml2:

../../lib/ephy-langs.c:228:52: error: pointer targets in passing argument 3 of 'xmlStrPrintf' differ in signedness [-Werror=pointer-sign]
   xmlStrPrintf (iso_entries, sizeof (iso_entries), (const xmlChar *)"iso_%d_entries", iso);